### ISSUE TITLE
Je projekt mrtvý ?

### ISSUE THREAD

**Issue by Vitexus** [xcross/flexibee#1]
Zdravím, 
Hledám knihovny v různých jazycích pro FlexiBee a našel jsem tu pro GO pouze torzo a to je škoda.
Bylo by prosím možné sem dát nějaké zdrojáky ?

**Comment by xcross** [comment]
Bohužel je to zatím vše co jsem napsal :(

Igor Černý

**Comment by Vitexus** [comment]
Děkuju za odpověď
Inu co se dá dělat, to je život ...
